import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, Pencil } from 'lucide-react';
import { getEmployee } from '@/lib/data/employees';
import { requireStaffCompany } from '@/lib/auth';
import { Button, Card } from '@/components/ui';
import { MemberStatusBadge, RoleBadge } from '@/components/member-badges';
import { StatusToggle } from '@/components/status-toggle';
import { ResendInvitation } from '@/components/resend-invitation';
import { setEmployeeActive } from '../actions';
import { canManageMember } from '@/lib/member-permissions';

function Info({ label, value }: { label: string; value?: string | number | null }) { return <div><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-medium text-slate-800">{value ?? '—'}</dd></div>; }

export default async function EmployeeDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string }> }) {
  const { id } = await params; const { success } = await searchParams;
  const [{ role: actorRole }, employee] = await Promise.all([requireStaffCompany(), getEmployee(id)]); if (!employee) notFound();
  const profile = (Array.isArray(employee.profiles) ? employee.profiles[0] : employee.profiles) as { first_name: string | null; last_name: string | null; phone: string | null; avatar_url: string | null } | null;
  const details = employee.employee_details?.[0]; const invitations = employee.company_invitations ?? []; const lastInvitation = invitations.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())[0];
  const name = [profile?.first_name ?? employee.invited_first_name, profile?.last_name ?? employee.invited_last_name].filter(Boolean).join(' ') || 'Mitarbeiter';
  const canManage = canManageMember(actorRole, employee.role as 'OFFICE' | 'EMPLOYEE');
  return <div className="mx-auto max-w-5xl"><Link href="/dashboard/mitarbeiter" className="mb-5 inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-teal-700"><ArrowLeft className="size-4" />Zurueck zu Mitarbeitern</Link>{success && <p className="mb-5 rounded-md bg-teal-50 p-3 text-sm text-teal-800">{success}</p>}<div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight">{name}</h1><RoleBadge role={employee.role as 'OFFICE' | 'EMPLOYEE'} /><MemberStatusBadge status={employee.status as 'INVITED' | 'ACTIVE' | 'DISABLED'} /></div><p className="mt-2 text-sm text-slate-600">{employee.invited_email}</p></div>{canManage && <div className="flex flex-wrap gap-3"><Link href={`/dashboard/mitarbeiter/${employee.id}/bearbeiten`}><Button variant="outline"><Pencil className="mr-2 size-4" />Bearbeiten</Button></Link>{employee.status === 'INVITED' ? <ResendInvitation memberId={employee.id} /> : <StatusToggle id={employee.id} isActive={employee.status === 'ACTIVE'} noun="Mitarbeiter" action={setEmployeeActive} />}</div>}</div>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Stammdaten</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Vorname" value={profile?.first_name ?? employee.invited_first_name} /><Info label="Nachname" value={profile?.last_name ?? employee.invited_last_name} /><Info label="E-Mail-Adresse" value={employee.invited_email} /><Info label="Telefon" value={profile?.phone ?? employee.invited_phone} /></dl></Card><Card className="p-5"><h2 className="font-semibold">Rolle & Status</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Rolle" value={employee.role === 'OFFICE' ? 'Buero' : 'Mitarbeiter'} /><Info label="Status" value={employee.status === 'ACTIVE' ? 'Aktiv' : employee.status === 'INVITED' ? 'Eingeladen' : 'Deaktiviert'} /></dl></Card><Card className="p-5"><h2 className="font-semibold">Arbeitsdaten</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Personalnummer" value={details?.employee_number} /><Info label="Wochenstunden" value={details?.weekly_hours != null ? `${details.weekly_hours} Stunden` : null} /><Info label="Eintrittsdatum" value={details?.employment_start_date} /><Info label="Aktiv" value={details?.is_active ? 'Ja' : details ? 'Nein' : null} /></dl>{details?.notes && <p className="mt-5 whitespace-pre-wrap border-t pt-5 text-sm text-slate-700">{details.notes}</p>}</Card><Card className="p-5"><h2 className="font-semibold">Account / Einladung</h2><dl className="mt-5 grid gap-5"><Info label="Einladungsstatus" value={employee.status === 'INVITED' ? `Gueltig bis ${lastInvitation?.expires_at ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(lastInvitation.expires_at)) : '—'}` : employee.joined_at ? `Beigetreten am ${new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium' }).format(new Date(employee.joined_at))}` : '—'} /><Info label="Deaktiviert am" value={employee.disabled_at ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium' }).format(new Date(employee.disabled_at)) : null} /></dl></Card></div>
  </div>;
}
