import Link from 'next/link';
import { Plus } from 'lucide-react';
import { Button, Card } from '@/components/ui';
import { JobPhotoGallery } from '@/components/job-photo-gallery';
import { JobPhotoUpload } from '@/components/job-photo-upload';
import { QualityInspectionForm } from '@/components/quality-inspection-form';
import { listComplaintFormOptions, listQualityInspections } from '@/lib/data/complaints';
import { listOperationalPhotos } from '@/lib/data/operational-photos';
import { createQualityInspection, deleteOperationalPhoto, uploadOperationalPhoto } from '../reklamationen/actions';

function first<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] ?? null : value; }
export default async function QualityInspectionsPage({ searchParams }: { searchParams: Promise<{ neu?: string }> }) {
  const { neu } = await searchParams; const [inspections, options] = await Promise.all([listQualityInspections(), listComplaintFormOptions()]);
  const photos = await Promise.all(inspections.map((inspection) => listOperationalPhotos('QUALITY_INSPECTION', inspection.id)));
  return <div className="mx-auto max-w-6xl"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-teal-700">Qualität</p><h1 className="mt-1 text-2xl font-semibold">Qualitätskontrolle</h1><p className="mt-2 text-sm text-slate-600">Prüfergebnisse für Objekte und Aufträge dokumentieren.</p></div><Link href="/dashboard/qualitaetskontrolle?neu=1"><Button><Plus className="mr-2 size-4" />Kontrolle erfassen</Button></Link></div>{neu === '1' && <Card className="mb-6 p-6"><h2 className="font-semibold">Neue Qualitätskontrolle</h2><div className="mt-5"><QualityInspectionForm objects={options.objects} jobs={options.jobs} action={createQualityInspection} /></div></Card>}<Card className="overflow-hidden">{inspections.length === 0 ? <div className="p-8 text-center"><p className="font-medium">Noch keine Qualitätskontrollen erfasst.</p><p className="mt-2 text-sm text-slate-600">Dokumentieren Sie Ergebnisse direkt nach der Objektprüfung.</p></div> : <div className="divide-y">{inspections.map((inspection, index) => { const object = first(inspection.cleaning_objects as never) as { name?: string } | null; const job = first(inspection.jobs as never) as { title?: string } | null; return <div className="p-5" key={inspection.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{object?.name ?? 'Objekt'}</p><p className="mt-1 text-sm text-slate-600">{job?.title ?? 'Objektkontrolle'}</p></div><div className={`rounded px-2 py-1 text-xs font-medium ${inspection.result === 'PASS' ? 'bg-teal-50 text-teal-800' : 'bg-red-100 text-red-800'}`}>{inspection.result === 'PASS' ? 'Bestanden' : 'Nicht bestanden'}{inspection.score != null ? ` · ${inspection.score}/100` : ''}</div></div><p className="mt-3 text-sm text-slate-700">{inspection.notes || 'Keine Notizen hinterlegt.'}</p>{inspection.follow_up_required && <p className="mt-2 text-xs font-medium text-amber-800">Nacharbeit erforderlich</p>}<div className="mt-5"><JobPhotoUpload action={uploadOperationalPhoto.bind(null, 'QUALITY_INSPECTION', inspection.id)} checklistItems={[]} /><JobPhotoGallery photos={photos[index] ?? []} canDelete={() => true} deleteAction={deleteOperationalPhoto} /></div></div>; })}</div>}</Card></div>;
}
