import Link from 'next/link';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { Card } from '@/components/ui';
import { ComplaintForm } from '@/components/complaint-form';
import { FollowUpJobForm } from '@/components/follow-up-job-form';
import { JobPhotoGallery } from '@/components/job-photo-gallery';
import { JobPhotoUpload } from '@/components/job-photo-upload';
import { getComplaint, listComplaintFormOptions } from '@/lib/data/complaints';
import { listOperationalPhotos } from '@/lib/data/operational-photos';
import { createFollowUpJob, deleteOperationalPhoto, updateComplaint, uploadOperationalPhoto } from '../actions';
import { notFound } from 'next/navigation';

function first<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] ?? null : value; }
function person(value: unknown) { const member = first(value as { profiles: { first_name: string | null; last_name: string | null } | { first_name: string | null; last_name: string | null }[] | null } | { profiles: { first_name: string | null; last_name: string | null } | { first_name: string | null; last_name: string | null }[] | null }[] | null); const profile = first(member?.profiles ?? null); return [profile?.first_name, profile?.last_name].filter(Boolean).join(' ') || 'Mitarbeiter'; }
export default async function ComplaintDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [record, options] = await Promise.all([getComplaint(id), listComplaintFormOptions()]); if (!record) notFound(); const [photos] = await Promise.all([listOperationalPhotos('COMPLAINT', id)]); const { complaint } = record; const job = first(complaint.jobs as never) as { id?: string; title?: string } | null;
  const employees = record.employees.map((employee) => ({ id: employee.id, name: person(employee) }));
  return <div className="mx-auto max-w-5xl"><Link href="/dashboard/reklamationen" className="mb-5 inline-flex items-center gap-2 text-sm text-slate-600"><ArrowLeft className="size-4" />Zurück zu Reklamationen</Link><div className="mb-6"><p className="text-sm font-medium text-teal-700">Reklamation</p><h1 className="mt-1 text-2xl font-semibold">{complaint.title}</h1></div><div className="grid gap-5 lg:grid-cols-3"><Card className="p-6 lg:col-span-2"><h2 className="font-semibold">Vorgang bearbeiten</h2><div className="mt-5"><ComplaintForm complaint={complaint} options={options} action={updateComplaint.bind(null, id)} submitLabel="Änderungen speichern" /></div></Card><div className="space-y-5"><Card className="p-5"><h2 className="font-semibold">Nacharbeit</h2>{complaint.follow_up_job_id ? <Link className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-teal-700 underline" href={`/dashboard/auftraege/${complaint.follow_up_job_id}`}>Nacharbeitsauftrag öffnen <ExternalLink className="size-4" /></Link> : <FollowUpJobForm action={createFollowUpJob.bind(null, id)} employees={employees} />}</Card><Card className="p-5"><h2 className="font-semibold">Verlauf</h2>{record.updates.length === 0 ? <p className="mt-3 text-sm text-slate-600">Noch keine operativen Aktualisierungen.</p> : <ul className="mt-3 space-y-4 text-sm">{record.updates.map((update) => <li key={update.id}><p className="font-medium">{person(update.company_members)}</p><p className="mt-1 text-slate-600">{update.note}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat('de-DE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(update.created_at))}</p></li>)}</ul>}</Card></div></div><div className="mt-6"><JobPhotoUpload action={uploadOperationalPhoto.bind(null, 'COMPLAINT', id)} checklistItems={[]} /><JobPhotoGallery photos={photos} canDelete={() => true} deleteAction={deleteOperationalPhoto} /></div>{job && <p className="mt-4 text-sm text-slate-600">Weitere auftragsbezogene Fotos sind im <Link className="font-medium text-teal-700 underline" href={`/dashboard/auftraege/${job.id}`}>Auftrag</Link> sichtbar.</p>}</div>;
}
