'use client';

import { useActionState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { type FormState, initialFormState } from '@/lib/actions';
import { Button, Input } from '@/components/ui';
import { FormMessage, SubmitButton } from '@/components/form-controls';

type ObjectRecord = { id?: string; customer_id?: string | null; name?: string | null; object_number?: string | null; street?: string | null; postal_code?: string | null; city?: string | null; country?: string | null; contact_first_name?: string | null; contact_last_name?: string | null; contact_phone?: string | null; contact_email?: string | null; area_sqm?: number | null; areas_description?: string | null; access_instructions?: string | null; cleaning_instructions?: string | null; notes?: string | null; };
type CustomerOption = { id: string; name: string; customer_number: string | null; is_active: boolean };
type ObjectAction = (state: FormState, formData: FormData) => Promise<FormState>;
const textareaClass = 'mt-1.5 flex h-28 w-full rounded-md border bg-white px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-primary';

export function CleaningObjectForm({ object, customers, action, submitLabel }: { object?: ObjectRecord; customers: CustomerOption[]; action: ObjectAction; submitLabel: string }) {
  const [state, formAction] = useActionState(action, initialFormState);
  const router = useRouter();
  useEffect(() => { if (state.status === 'success' && state.id) router.push(`/dashboard/objekte/${state.id}?success=${encodeURIComponent('Objekt wurde gespeichert.')}`); }, [router, state]);
  return <form action={formAction} className="space-y-7"><FormMessage status={state.status} message={state.message} />
    <section className="grid gap-5 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Allgemein</h2><label className="block text-sm font-medium sm:col-span-2">Kunde <span className="text-red-700">*</span><select className="mt-1.5 flex h-10 w-full rounded-md border bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary" name="customer_id" defaultValue={object?.customer_id ?? ''} required><option value="" disabled>Kunde auswaehlen</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}{customer.customer_number ? ` (${customer.customer_number})` : ''}</option>)}</select></label><label className="block text-sm font-medium">Objektname <span className="text-red-700">*</span><Input className="mt-1.5" name="name" defaultValue={object?.name ?? ''} maxLength={160} required /></label><label className="block text-sm font-medium">Objektnummer<Input className="mt-1.5" name="object_number" defaultValue={object?.object_number ?? ''} placeholder="Automatisch, z. B. O-0001" maxLength={64} /></label></section>
    <section className="border-t pt-6"><h2 className="font-semibold">Adresse</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium sm:col-span-2">Strasse und Hausnummer<Input className="mt-1.5" name="street" defaultValue={object?.street ?? ''} maxLength={240} /></label><label className="block text-sm font-medium">Postleitzahl<Input className="mt-1.5" name="postal_code" defaultValue={object?.postal_code ?? ''} maxLength={16} /></label><label className="block text-sm font-medium">Ort<Input className="mt-1.5" name="city" defaultValue={object?.city ?? ''} maxLength={120} /></label><label className="block text-sm font-medium">Land<Input className="mt-1.5" name="country" defaultValue={object?.country ?? 'Deutschland'} maxLength={120} /></label></div></section>
    <section className="border-t pt-6"><h2 className="font-semibold">Kontakt vor Ort</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Vorname<Input className="mt-1.5" name="contact_first_name" defaultValue={object?.contact_first_name ?? ''} maxLength={120} /></label><label className="block text-sm font-medium">Nachname<Input className="mt-1.5" name="contact_last_name" defaultValue={object?.contact_last_name ?? ''} maxLength={120} /></label><label className="block text-sm font-medium">Telefon<Input className="mt-1.5" name="contact_phone" type="tel" defaultValue={object?.contact_phone ?? ''} maxLength={64} /></label><label className="block text-sm font-medium">E-Mail<Input className="mt-1.5" name="contact_email" type="email" defaultValue={object?.contact_email ?? ''} maxLength={254} /></label></div></section>
    <section className="grid gap-5 border-t pt-6"><h2 className="font-semibold">Objektinformationen</h2><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Flaeche in m2<Input className="mt-1.5" name="area_sqm" type="number" min="0.01" step="0.01" defaultValue={object?.area_sqm ?? ''} /></label><label className="block text-sm font-medium">Etagen / Bereiche<Input className="mt-1.5" name="areas_description" defaultValue={object?.areas_description ?? ''} maxLength={500} /></label></div><label className="block text-sm font-medium">Zugangshinweise<textarea className={textareaClass} name="access_instructions" defaultValue={object?.access_instructions ?? ''} maxLength={4000} /><span className="mt-1 block text-xs text-slate-500">Keine Alarmcodes, Passwoerter oder PINs speichern.</span></label><label className="block text-sm font-medium">Reinigungsanweisungen<textarea className={textareaClass} name="cleaning_instructions" defaultValue={object?.cleaning_instructions ?? ''} maxLength={4000} /></label><label className="block text-sm font-medium">Interne Notizen<textarea className={textareaClass} name="notes" defaultValue={object?.notes ?? ''} maxLength={4000} /></label></section>
    <div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => router.back()}>Abbrechen</Button><SubmitButton>{submitLabel}</SubmitButton></div>
  </form>;
}
