'use client';

import { useActionState, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { type FormState, initialFormState } from '@/lib/actions';
import { Button, Input } from '@/components/ui';
import { FormMessage, SubmitButton } from '@/components/form-controls';

type Option = { id: string; name: string; customer_id?: string; is_active?: boolean };
type Employee = { id: string; profiles: { first_name: string | null; last_name: string | null } | { first_name: string | null; last_name: string | null }[] | null };
type JobRecord = { id?: string; customer_id?: string; cleaning_object_id?: string; checklist_template_id?: string | null; title?: string; description?: string | null; scheduled_date?: string; planned_start_at?: string; planned_end_at?: string; status?: string; priority?: string; internal_notes?: string | null; employee_instructions?: string | null; job_assignments?: { member_id: string }[] };
type JobAction = (state: FormState, data: FormData) => Promise<FormState>;
function time(value?: string) { return value ? new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Europe/Berlin' }).format(new Date(value)) : ''; }
function employeeName(employee: Employee) { const profile = Array.isArray(employee.profiles) ? employee.profiles[0] : employee.profiles; return [profile?.first_name, profile?.last_name].filter(Boolean).join(' ') || 'Mitarbeiter'; }

export function JobForm({ job, customers, objects, employees, templates, action, submitLabel }: { job?: JobRecord; customers: Option[]; objects: Option[]; employees: Employee[]; templates: { id: string; name: string }[]; action: JobAction; submitLabel: string }) {
  const [state, formAction] = useActionState(action, initialFormState); const router = useRouter(); const [customerId, setCustomerId] = useState(job?.customer_id ?? '');
  useEffect(() => { if (state.status === 'success' && state.id) router.push(`/dashboard/auftraege/${state.id}?success=${encodeURIComponent('Auftrag wurde gespeichert.')}`); }, [router, state]);
  const selectedMembers = new Set(job?.job_assignments?.map((item) => item.member_id) ?? []); const availableObjects = objects.filter((object) => object.customer_id === customerId);
  return <form action={formAction} className="space-y-7"><FormMessage status={state.status} message={state.message} />{state.conflictWarning && <label className="block rounded-md bg-amber-50 p-4 text-sm text-amber-900"><strong>Planungskonflikt:</strong> {state.conflictWarning}<span className="mt-3 flex items-center gap-2"><input name="confirm_conflicts" value="true" type="checkbox" /> Trotzdem speichern</span></label>}
    <section className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Kunde <span className="text-red-700">*</span><select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="customer_id" defaultValue={customerId} onChange={(event) => setCustomerId(event.target.value)} required><option value="" disabled>Kunde auswaehlen</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label className="block text-sm font-medium">Objekt <span className="text-red-700">*</span><select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="cleaning_object_id" defaultValue={job?.cleaning_object_id ?? ''} required><option value="" disabled>Objekt auswaehlen</option>{availableObjects.map((object) => <option key={object.id} value={object.id}>{object.name}</option>)}</select></label><label className="block text-sm font-medium sm:col-span-2">Titel <span className="text-red-700">*</span><Input className="mt-1.5" name="title" defaultValue={job?.title ?? ''} required maxLength={160} /></label><label className="block text-sm font-medium sm:col-span-2">Beschreibung<textarea className="mt-1.5 h-24 w-full rounded-md border bg-white p-3 text-sm" name="description" defaultValue={job?.description ?? ''} maxLength={4000} /></label></section>
    <section className="grid gap-5 border-t pt-6 sm:grid-cols-2"><label className="block text-sm font-medium">Datum <span className="text-red-700">*</span><Input className="mt-1.5" name="scheduled_date" type="date" defaultValue={job?.scheduled_date ?? ''} required /></label><label className="block text-sm font-medium">Status<select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="status" defaultValue={job?.status ?? 'PLANNED'}><option value="PLANNED">Geplant</option><option value="CONFIRMED">Bestaetigt</option><option value="CANCELLED">Storniert</option></select></label><label className="block text-sm font-medium">Geplanter Beginn <Input className="mt-1.5" name="planned_start_time" type="time" defaultValue={time(job?.planned_start_at)} required /></label><label className="block text-sm font-medium">Geplantes Ende <Input className="mt-1.5" name="planned_end_time" type="time" defaultValue={time(job?.planned_end_at)} required /></label><label className="block text-sm font-medium">Prioritaet<select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="priority" defaultValue={job?.priority ?? 'NORMAL'}><option value="LOW">Niedrig</option><option value="NORMAL">Normal</option><option value="HIGH">Hoch</option><option value="URGENT">Dringend</option></select></label><label className="block text-sm font-medium">Checkliste<select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="checklist_template_id" defaultValue={job?.checklist_template_id ?? ''}><option value="">Objektstandard verwenden</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label></section>
    <section className="border-t pt-6"><h2 className="font-semibold">Mitarbeiter</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{employees.map((employee) => <label key={employee.id} className="flex items-center gap-3 rounded-md border p-3 text-sm"><input type="checkbox" name="member_ids" value={employee.id} defaultChecked={selectedMembers.has(employee.id)} />{employeeName(employee)}</label>)}</div></section>
    <section className="grid gap-5 border-t pt-6"><label className="block text-sm font-medium">Arbeitsanweisung<textarea className="mt-1.5 h-24 w-full rounded-md border bg-white p-3 text-sm" name="employee_instructions" defaultValue={job?.employee_instructions ?? ''} maxLength={4000} /></label><label className="block text-sm font-medium">Interne Notiz<textarea className="mt-1.5 h-24 w-full rounded-md border bg-white p-3 text-sm" name="internal_notes" defaultValue={job?.internal_notes ?? ''} maxLength={4000} /></label></section>
    <div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => router.back()}>Abbrechen</Button><SubmitButton>{submitLabel}</SubmitButton></div>
  </form>;
}
