'use client';

import { useActionState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Input } from '@/components/ui';
import { FormMessage, SubmitButton } from '@/components/form-controls';
import { initialFormState, type FormState } from '@/lib/actions';

type Action = (state: FormState, formData: FormData) => Promise<FormState>;
export function QualityInspectionForm({ objects, jobs, action }: { objects: { id: string; name: string }[]; jobs: { id: string; cleaning_object_id: string; title: string; scheduled_date: string }[]; action: Action }) {
  const [state, formAction] = useActionState(action, initialFormState); const router = useRouter();
  useEffect(() => { if (state.status === 'success') router.push('/dashboard/qualitaetskontrolle'); }, [router, state]);
  return <form action={formAction} className="space-y-6"><FormMessage status={state.status} message={state.message} /><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Objekt <span className="text-red-700">*</span><select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="cleaning_object_id" required defaultValue=""><option value="" disabled>Objekt auswählen</option>{objects.map((object) => <option key={object.id} value={object.id}>{object.name}</option>)}</select></label><label className="block text-sm font-medium">Auftrag<select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="job_id" defaultValue=""><option value="">Kein Auftrag verknüpft</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.scheduled_date}: {job.title}</option>)}</select></label><label className="block text-sm font-medium">Prüfdatum <span className="text-red-700">*</span><Input className="mt-1.5" name="inspected_at" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label className="block text-sm font-medium">Ergebnis <select className="mt-1.5 h-10 w-full rounded-md border bg-white px-3 text-sm" name="result" defaultValue="PASS"><option value="PASS">Bestanden</option><option value="FAIL">Nicht bestanden</option></select></label><label className="block text-sm font-medium">Bewertung (0-100)<Input className="mt-1.5" name="score" type="number" min="0" max="100" /></label><label className="flex items-end gap-2 pb-2 text-sm font-medium"><input name="follow_up_required" type="checkbox" /> Nacharbeit erforderlich</label><label className="block text-sm font-medium sm:col-span-2">Prüfkriterien <span className="text-slate-500">(eine Zeile pro Kriterium)</span><textarea className="mt-1.5 min-h-28 w-full rounded-md border bg-white px-3 py-2 text-sm" name="criteria" maxLength={4000} /></label><label className="block text-sm font-medium sm:col-span-2">Notizen<textarea className="mt-1.5 min-h-28 w-full rounded-md border bg-white px-3 py-2 text-sm" name="notes" maxLength={4000} /></label></div><div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => router.back()}>Abbrechen</Button><SubmitButton>Qualitätskontrolle speichern</SubmitButton></div></form>;
}
